configure: check base dependence for compile
Signed-off-by: lonelywetp <wetp.zy@linux.alibaba.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,7 @@ static_link=no
 enable_all=no
 default_target=yes
 check_bpf_support=no
+kernel_bpf_support=NO
 
 usage() {
 	echo "Usage: configure [options]"
@@ -22,6 +23,61 @@ usage() {
 	echo "  --enable-target-all        enable all compoents"
 	echo "  --disable-default          disable default compoents to built-in"
 	echo "  --show-target              list all support tools"
+}
+
+check_bpf_kernel() {
+	kern_major=$(echo $kern_ver | awk -F '.' '{print $1}')
+	kern_minor=$(echo $kern_ver | awk -F '.' '{print $2}')
+	is_centos7=$(echo $kern_ver | grep el7 | wc -l)
+
+	if [ $((kern_major)) -ge 4 -a $((kern_minor)) -ge 4 ]; then
+		kernel_bpf_support="YES"
+	fi
+
+	if [ $is_centos7 = 1 ]; then
+		centos_minor=$(echo $kern_ver | awk -F '-' '{print $2}' | awk -F '.' '{print $1}')
+		if [ $((centos_minor)) -ge 957 ];then
+			kernel_bpf_support="YES"
+		fi
+	fi
+
+	if [ $kernel_bpf_support != "YES" ];then
+		echo "this kernel version not support ebpf"
+	fi
+}
+
+check_bpf_depend() {
+	local bpf_ok="no"
+
+	check_bpf_kernel
+	if [ $kernel_bpf_support = "YES" ];then
+		rpm -q clang > /dev/null
+		if [ $? = 0 ];then
+			bpf_ok="yes"
+		else
+			echo "check clang failed, should intall first"
+		fi
+	fi
+	if [ $bpf_ok != "yes" -a $enable_libbpf = "YES" ]; then
+		exit 1
+	fi
+}
+
+check_lkm_depend() {
+	rpm -q kernel-devel-$kern_ver > /dev/null
+	if [ $? != 0 ];then
+		echo "check kernel-devel-$kern_ver failed, should intall first"
+		exit 1;
+	fi
+}
+
+check_depend() {
+	if [ $enable_lkm = "YES" ]; then
+		check_lkm_depend
+	fi
+	if [ $check_bpf_support = "yes" -o $enable_libbpf = "YES" ]; then
+		check_bpf_depend
+	fi
 }
 
 for opt; do
@@ -66,28 +122,7 @@ for opt; do
 	esac
 done
 
-if [ $check_bpf_support = "yes" -a $enable_libbpf = NO ]; then
-kern_major=$(echo $kern_ver | awk -F '.' '{print $1}')
-kern_minor=$(echo $kern_ver | awk -F '.' '{print $2}')
-is_alios=$(echo $kern_ver | grep alios | wc -l)
-is_centos7=$(echo $kern_ver | grep el7 | wc -l)
-
-if [ $((kern_major)) -ge 4 -a $((kern_minor)) -ge 4 ]; then
-	enable_libbpf="YES"
-fi
-
-if [ $is_alios = 1 ]; then
-	enable_libbpf="NO"
-fi
-
-if [ $is_centos7 = 1 ]; then
-	centos_minor=$(echo $kern_ver | awk -F '-' '{print $2}' | awk -F '.' '{print $1}')
-	if [ $((centos_minor)) -ge 957 ];then
-		enable_libbpf="YES"
-	fi
-fi
-
-fi
+check_depend
 
 echo "# Automatically generated by configure - do not modify" > $config_host_mak
 
